### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by prisonblues** [benbalter/bulk-issue-creator#7]
### Describe the bug

I am getting the following error on the `bulk create issues` step, am I doing something wrong?

```
Run benbalter/bulk-issue-creator@main
/usr/bin/docker run --name c044242be5fa4e1de4e5fa51[6](https://github.com/username/repo-name/actions/runs/4539606879/jobs/7999631349#step:4:7)bc0d2e[7](https://github.com/username/repo-name/actions/runs/4539606879/jobs/7999631349#step:4:8)d1bd9_1e[8](https://github.com/username/repo-name/actions/runs/4539606879/jobs/7999631349#step:4:9)807 --label 6c0442 --workdir /github/workspace --rm -e "GITHUB_TOKEN" -e "INPUT_WRITE" -e "INPUT_COMMENT" -e "INPUT_TEMPLATE_PATH" -e "INPUT_CSV_PATH" -e "INPUT_GITHUB_TOKEN" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/repo-name/repo-name":"/github/workspace" 6c0442:42be5fa4e1de4e5fa516bc0d2e7d1bd[9](https://github.com/username/repo-name/actions/runs/4539606879/jobs/7999631349#step:4:10)  "false" "" "" "" ""
fatal: not a git repository (or any of the parent directories): .git
To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
/usr/src/app/lib/bulk_issue_creator.rb:[10](https://github.com/username/repo-name/actions/runs/4539606879/jobs/7999631349#step:4:11)4:in `ensure_path_exists': Expected /github/workspace/config/template.md.mustache to exist (BulkIssueCreator::MissingFileError)
	from /usr/src/app/lib/bulk_issue_creator.rb:64:in `run'
	from /usr/src/app/bin/bulk-issue-creator:21:in `create'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/invocation.rb:[12](https://github.com/username/repo-name/actions/runs/4539606879/jobs/7999631349#step:4:13)7:in `invoke_command'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /usr/local/bundle/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	from /usr/src/app/bin/bulk-issue-creator:51:in `<main>'
I, [[20](https://github.com/username/repo-name/actions/runs/4539606879/jobs/7999631349#step:4:21)23-03-28T05:28:59.40[22](https://github.com/username/repo-name/actions/runs/4539606879/jobs/7999631349#step:4:23)02 #8]  INFO -- : Running with the following options:
---
template_path: 
csv_path: 
write: false
comment: false

```
`
### Steps to reproduce the behavior

Follow the instructions (just doing1 repository, so no API key)

**Comment by benbalter** [comment]
` Expected /github/workspace/config/template.md.mustache to exist (BulkIssueCreator::MissingFileError)
	from /usr/src/app/lib/bulk_issue_creator.rb:64:in `run'`

**Comment by prisonblues** [comment]
Sorry, I am an idiot - and thanks.
